### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by harsh726** [akshaychandra21/Alphabet_Recognition_RealTime#5]
Using TensorFlow backend.
Traceback (most recent call last):
  File "E:\Projects\Alphabet_Recognition_Gestures-master\cnn_model_builder.py", line 7, in <module>
    from mnist import MNIST
ImportError: cannot import name 'MNIST' from 'mnist' (E:\CSUSM\Sem_2\Python\lib\site-packages\mnist\__init__.py)

**Comment by harsh726** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "E:\Projects\Umangi\Real Time Text Recognition\Real_Time_Text_Recognition.py", line 32, in <module>
    cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by harsh726** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "E:\Last Sem\Computer Vision\Final Project\Alphabet_Recognition_Gestures-master\Alphabet_Recognition_Gestures-master\alphabet_recognition.py", line 78, in <module>
    if len(blackboard_cnts) >= 1:
TypeError: object of type 'NoneType' has no len()

**Comment by jaspreetmonga** [comment]
I solved the errors.
feel free to ping.
Good luck!

**Comment by Cheeriooo** [comment]
@jaspreetmonga  hello 
Can you help with the issue of the opencv window , abruptly closing 
there are either of the follwing errors  occuring -
->   if len(blackboard_cnts) >= 1:
TypeError: object of type 'NoneType' has no len()



-> File "C:\Users\lenovo\Desktop\SUBLIME\Alphabet Recognition\alphabet_recognition.py", line 79, in <module>
    cnt = sorted(blackboard_cnts, key = cv2.contourArea, reverse = True)[0]
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-6lylwdcz\opencv\modules\imgproc\src\shapedescr.cpp:315: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

thanks
